### PR TITLE
fix small typo on part3_neural_network_mnist_and_own_single_image.ipy…

### PR DESCRIPTION
**Pull request by cafornaca**
…nb #8

"withour" -> "with our"

### CODE REVIEW

**Comment by makeyourownneuralnetwork** [comment]
:)

**Comment by cafornaca** [comment]
Love the book~ Thank you so much for provided the code from it!

**Comment by makeyourownneuralnetwork** [comment]
thanks! feel free to add a short amazon review if you like the book (it helps invest in my next book)

**Comment by ahurtado23** [comment]
i executed this code and it seems the neural network keeps getting it wrong :( 

do you think it's something with the data set?

**Comment by ahurtado23** [comment]
screen shot 2018-12-16 at 12 07 05 pm

**Comment by makeyourownneuralnetwork** [comment]
Hi @ahurtado23 - thanks for the question.

Which data are you using? Is it your own? How did you make it? Can yo provide an example image from your dataset?

That will help me try to find the error.

PS - the neural network isn't perfect but should still be correct most of the time.

**Comment by ahurtado23** [comment]
It’s from your mnist folder!

Step by step!

**Comment by makeyourownneuralnetwork** [comment]
i downloaded a fresh copy of the code and data from github and the [website](https://pjreddie.com/projects/mnist-in-csv/) providing the CSV sources of training and test data ..

It seems to work for me. See image below.

This suggests that there might be some step that is different. 

I don't always get perfect results - sometimes the network is wrong, but the error rate shouldn't be too high.

screenshot 2018-12-18 at 03 33 19

**Comment by ahurtado23** [comment]
I downloaded a fresh copy of the mnst data sets and it seems to be working
perfect!

**Pull request merged**
